import { AnimationStateFull } from './bindings/AnimationStateFull';

/**
 * Interface Integrity Checker
 * This tool performs a runtime validation of the data received from the Rust WASM engine
 * against the TypeScript definitions generated by ts-rs.
 */
export class IntegrityChecker {
    /**
     * Validates a raw object from the engine against the expected AnimationStateFull structure.
     * Since TypeScript interfaces are erased at runtime, this performs structural validation.
     */
    static validateState(rawState: any): { valid: boolean; errors: string[] } {
        const errors: string[] = [];

        if (!rawState) {
            errors.push("Root state object is null or undefined.");
            return { valid: false, errors };
        }

        // 1. Check top-level wrapper
        if (!('animation' in rawState)) errors.push("Missing 'animation' field in root state.");
        if (!('imgcut' in rawState)) errors.push("Missing 'imgcut' field in root state.");
        if (!('status' in rawState)) errors.push("Missing 'status' field in root state.");

        const anim = rawState.animation;
        if (anim) {
            // 2. Check critical animation fields
            if (!Array.isArray(anim.parts)) errors.push("animation.parts is not an array.");
            if (typeof anim.current_frame !== 'number') errors.push("animation.current_frame is not a number.");
            if (typeof anim.max_frame !== 'number') errors.push("animation.max_frame is not a number.");
            
            // 3. Check sample part structure
            if (anim.parts.length > 0) {
                const part = anim.parts[0];
                const requiredPartFields = ['index', 'name', 'x', 'y', 'z', 'raw_args'];
                requiredPartFields.forEach(f => {
                    if (!(f in part)) errors.push(`Sample part missing field: ${f}`);
                });
            }
        }

        const imgcut = rawState.imgcut;
        if (imgcut) {
            if (!Array.isArray(imgcut.cuts)) errors.push("imgcut.cuts is not an array.");
            if (!Array.isArray(imgcut.strs)) errors.push("imgcut.strs is not an array.");
        }

        return {
            valid: errors.length === 0,
            errors
        };
    }

    /**
     * Logs the integrity report to the console.
     */
    static logReport(rawState: any) {
        const result = this.validateState(rawState);
        if (result.valid) {
            console.log("%c[Integrity] Interface Check Passed: OK", "color: #10b981; font-weight: bold;");
        } else {
            console.error("%c[Integrity] Interface Mismatch Detected!", "color: #ef4444; font-weight: bold;");
            result.errors.forEach(err => console.warn(` -> ${err}`));
            console.log("Actual Structure Received:", rawState);
        }
    }
}
