// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixedPoint } from "./FixedPoint";

export type Vec2 = { x: FixedPoint, y: FixedPoint, };