// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationState } from "./AnimationState";
import type { ImgCut } from "./ImgCut";

export type AnimationStateFull = { status: string, animation: AnimationState, imgcut: ImgCut, };