// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Part } from './Part';

export type MaAnim = {
  n: number;
  parts: Array<Part>;
  max: number;
  len: number;
};
