// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PartTransform = { x: number, y: number, scale_x: number, scale_y: number, angle: number, };