// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Part = {
  ints: [number, number, number, number, number];
  name: string;
  n: number;
  max: number;
  off: number;
  fir: number;
  moves: Array<[number, number, number, number]>;
};
