[package]
name = "bcu-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bcu-core = { workspace = true }
bcu-render = { workspace = true }
bcu-assets = { workspace = true }
bcu-math = { workspace = true }
bcu-parser = { workspace = true }
wgpu = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }
console_error_panic_hook = { workspace = true }
log = { workspace = true }
wasm-bindgen-futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
