// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaAnim } from "./MaAnim";
import type { PartState } from "./PartState";

export type AnimationState = { current_frame: number, max_frame: number, parts: Array<PartState>, anim: MaAnim, };