// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PartState = { index: number, name: string, parent: number, z_order: number, raw_args: [number, number, number, number, number, number, number, number, number, number, number, number, number, number], };