// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixedPoint } from "./FixedPoint";
import type { Vec2 } from "./Vec2";

export type RenderState = { pos: Vec2, sca: Vec2, angle: FixedPoint, opacity: FixedPoint, img: number, z: number, };